data_key = "d0g82mox3es_Lsp4NdrMNBHadjTxPVVS7662CUAtYbXF"

[connections.supabase]
SUPABASE_URL = "https://1kuqqijnmzrikzkodqsiv.supabase.co"
SUPABASE_KEY = "1eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1cXFpam5tenJpa3prb2Rxc2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTE2MjM3OTcsImV4cCI6MjAyNzE5OTc5N30.B-mXWnwqDP2BcUgp0oVfphbrls26h4aRaa1NVkpvx-M"
